export enum AgentType {
  ADS = 'ADS',
  SSIAP1 = 'SSIAP1',
  SSIAP2 = 'SSIAP2',
  SSIAP3 = 'SSIAP3',
  CHEF_DE_POSTE = 'CHEF_DE_POSTE',
  CHEF_DE_EQUIPE = 'CHEF_DE_EQUIPE',
  RONDE = 'RONDE',
  ASTREINTE = 'ASTREINTE',
  FORMATION = 'FORMATION'
}